export const SET_USER = "user/auth/SET_USER"
export const CLEAR_USER = "user/auth/CLEAR_USER"
export const ADD_FEED_TO_USER = "user/feed/ADD"
export const DELETE_FEED = "user/feed/DELETE"
export const CHANGE_INTEREST_QUERY_CONTENT = "summary/feeds/CHANGE_INTEREST_QUERY_CONTENT"
export const CHANGE_PLAYBACK_SPEED = "summary/feeds/CHANGE_PLAYBACK_SPEED"